[tox]
minversion = 4.0
envlist = py314
isolated_build = true

[testenv]
description = Executa a suíte completa de testes no ambiente isolado via Poetry
package = wheel
allowlist_externals = poetry
setenv =
    RUSTFS_ROOT_USER = test-user
    RUSTFS_ROOT_PASSWORD = test-password
commands_pre =
    poetry install --with dev
commands =
    poetry run pytest -v {posargs}